### ISSUE TITLE
Error: something is wrong after github login

### ISSUE THREAD

**Issue by mworks-proj** [tierrun/tier-vercel-openai#14]
Hello,

I have made several attempts to resolve the issue, but it persists. My next course of action will involve overriding the next-auth module, as it appears to be the source of a login and verification error. I have successfully deployed the application multiple times, ensuring that the database is functioning correctly, Stripe integration is working, and updated pricing is displayed accurately. However, the error only manifests when attempting to log in, and it occurs almost immediately upon re-login.

To address this issue, I propose the following steps:

    Reproduction: Clone the project from Vercel.
    Verify that all environmental variables are correctly configured.
    Review all login URLs for GitHub OAuth integration.
    Test the application on a new laptop that has never visited the website (project.vercel.app).
    Create a new GitHub account and observe that the app starts to display its UI but then crashes without displaying any code.

Upon closer examination, I have noticed that there is an API endpoint located at pages/marketing & /api/generate that calls to the main repository. These API calls are causing errors locally when rendering the page and may be the reason for the crashes. It's worth noting that the API usage on api/generate appears to be exhausted, indicating that it's making two API calls on the same page: one for tier data from the original repository and another for tier.run/stripe products.

I suggest investigating whether an update is required for the next-auth module to resolve the login issue. Additionally, we should consider whether it's necessary to retain the tier-api metadata for the original repository. It appears that fetching this metadata on every page/marketing click might be excessive and could contribute to performance issues.

Let's address these issues systematically to ensure the stability and efficiency of the application.

**Comment by jerriclynsjohn** [comment]
I'm not able to recreate this problem. The next auth module perfectly fine and I'm able to log in and complete a subscription as well.

**Comment by jerriclynsjohn** [comment]
Can you join our community in Slack and DM me, we might need to exchange some secrets to get this sorted. https://tier.run/slack

**Comment by mworks-proj** [comment]
> well.

Can you share the link to your working repo,

**Comment by mworks-proj** [comment]
> Can you join our community in Slack and DM me, we might need to exchange some secrets to get this sorted. https://tier.run/slack

Can you share link again? I'm revisiting this idea looking to resolve the auth.  Thanks
