### ISSUE TITLE
Payment failed

### ISSUE THREAD

**Issue by SalahBioPhysics** [tierrun/tier-vercel-openai#15]
Payment fail after user subscribe to the non-free plans. Can this be because the site send the user to an **upgrade**/change plan? When the user get the free plan, the "payment" goes through but not when the user upgrade the plan. Also when the user buys the non-free plan, the site doesn't subscribe the user to that plan, instead it subscribe the user to the free plan, then the user can upgrade to other plans but the payment doesn't go through on Stripe.

**Comment by jerriclynsjohn** [comment]
Okay can you share a basic reproducible repo, so that i can check these out and come out with a solution for you.

**Comment by SalahBioPhysics** [comment]
I recopied the repo into a different project and now the payment works fine. Thank you!
