### ISSUE TITLE
First run

### ISSUE THREAD

**Issue by xapss** [tierrun/tier-vercel-openai#5]
I think I followed all steps, but I'm getting the following error when trying to load the pricing page:

```
- error src/config/subscriptionPlans.ts (96:26) @ currency
- error Error [TypeError]: Cannot read properties of undefined (reading 'currency')
    at eval (webpack-internal:///(sc_server)/./src/config/subscriptionPlans.ts:87:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: undefined
}
  94 
```

Any clue what I'm missing? I've added all the env. How am I getting the tier plans connected?

**Comment by m5k** [comment]
I had trouble with this as well. The resolution was to go into Stripe / Products, delete everything associated with the project, then also delete the archive of each deleted product (critical step). Clone the test tier.run again and push. Worked like a charm. Being that I was not familiar with how tier.run worked I screed up the initial push. Be careful with the pull/push function, read the docs!
